[project]
name = "tool-calling"
version = "0.1.0"
description = "Tool calling agent"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai-agents>=0.2.8",
    "tavily-python>=0.7.11",
]
